# -*- coding: utf-8 -*-
"""project1_single_gps_satellite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBLrk7dqecC5d8x45xj9oOTAH-sHEyi0

=============================================================================
🛰️ Project 1 — Single GPS Satellite Analysis
=============================================================================
 Author   : Hakim El Azzouzi
 Degree   : MSc Global Navigation Satellite Systems
            Mohammed First University, Oujda, Morocco
 Email    : elazzouzihakim10@gmail.com
 LinkedIn : https://linkedin.com/in/Hakim-El-Azzouzi
 Location : Luxembourg 🇱🇺
-----------------------------------------------------------------------------
 Station  : AUCK00NZL  —  Auckland, New Zealand  (GeoNet / LINZ Network)
 File     : AUCK00NZL_R_20260010000_01D_30S_MO.rnx
 Receiver : TRIMBLE ALLOY
 Antenna: TRM115000.00
 Format   : RINEX 3.05  |  Mixed Constellations  |  30-second sampling
 Date     : 2026-01-01  (Day-of-Year 001)
-----------------------------------------------------------------------------
 Description
 -----------
 This project focuses on a single GPS satellite tracked over 24 hours from the
 AUCK00NZL reference station in Auckland, New Zealand
 -----------------------------------------------------------------------------
 **About the projects**
 ----------------------
# Step1: Install & Import Libraries
# Step2: Load the RINEX File
# Step3: Selecting One Satellite
# Step4: Plot 1: Pseudorange Arc + SNR Time Series
# Step5: Plot 2: SNR Heatmap (Satellite Availability)
"""

# ──────────────────────────────────────────────────────────
# Step 1 — Install & Import Libraries
# ──────────────────────────────────────────────────────────
# Install georinex if not already installed
# Uncomment the line below if you are running this for the first time:
# !pip install --upgrade georinex

import georinex as gr
import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.colors import LinearSegmentedColormap
import warnings

warnings.filterwarnings('ignore')  # suppress xarray FutureWarnings during load

# Global plot style (dark GNSS theme)
plt.rcParams.update({
    'figure.dpi': 120,
    'axes.grid': True,
    'grid.alpha': 0.3,
})

print('✅ All libraries loaded successfully')
print(f'   georinex version : {gr.__version__}')
print(f'   xarray version   : {xr.__version__}')

# ─────────────────────────────────────────────────────────────────
# Step 2 — Load the RINEX File
# ─────────────────────────────────────────────────────────────────
# RINEX FILE PATH HERE
obs_path = "/AUCK00NZL_R_20260010000_01D_30S_MO.rnx"  # ← change this path
# Read the file header first (fast — no data loaded yet)
print("📋 FILE HEADER")
print("=" * 60)
header = gr.rinexheader(obs_path)

for key, value in header.items():
    print(f"{key:<25}: {value}")

print()

# Load all observation data (interval=30 means keep 30-sec rate)

print("⏳ Loading observation data (this may take 1–2 minutes)...")
obs = gr.load(obs_path, interval=30)
print()
print("✅ Data loaded!")
print(obs)

# ─────────────────────────────────────────────────────────────────
# Step 3 — Selecting One Satellite
# ─────────────────────────────────────────────────────────────────
# List all GPS satellites present in the file
all_sv = obs.sv.values
gps_sats = sorted([s for s in all_sv if s.startswith('G')])

print(f"🛰️  GPS satellites in this file ({len(gps_sats)} total):")
print("   " + "  ".join(gps_sats))
print()

# 👉 Selecting One Satellite Here
SAT = 'G05'   # ← change this to any GPS satellite listed above

# Pseudorange: which observable to use?
# C1C = L1 C/A code pseudorange (most common for GPS)
# C1X = L1 combined pseudorange (used by some receivers)
# We try C1C first, then fall back to C1X if not available.
if 'C1C' in obs.data_vars:
    pr = obs['C1C'].sel(sv=SAT).to_series().dropna()
    pr_label = 'C1C'
elif 'C1X' in obs.data_vars:
    pr = obs['C1X'].sel(sv=SAT).to_series().dropna()
    pr_label = 'C1X'
else:
    raise ValueError("No C1C or C1X observable found in this file.")

# SNR: which observable to use?
if 'S1C' in obs.data_vars:
    snr = obs['S1C'].sel(sv=SAT).to_series().dropna()
    snr_label = 'S1C'
elif 'S1X' in obs.data_vars:
    snr = obs['S1X'].sel(sv=SAT).to_series().dropna()
    snr_label = 'S1X'
else:
    raise ValueError("No S1C or S1X observable found in this file.")

print(f"✅ Selected satellite : {SAT}")
print(f"   Pseudorange obs   : {pr_label}  ({len(pr)} valid epochs)")
print(f"   SNR obs           : {snr_label}  ({len(snr)} valid epochs)")
print()
print(f"📊 Pseudorange statistics:")
print(f"   Min  : {pr.min()/1e6:.3f} Mm")
print(f"   Max  : {pr.max()/1e6:.3f} Mm")
print(f"   Mean : {pr.mean()/1e6:.3f} Mm")
print()
print(f"📊 SNR statistics:")
print(f"   Min  : {snr.min():.1f} dB-Hz")
print(f"   Max  : {snr.max():.1f} dB-Hz")
print(f"   Mean : {snr.mean():.1f} dB-Hz")

# ─────────────────────────────────────────────
# Step 4 — Plot 1: Pseudorange Arc + SNR Time Series
# ─────────────────────────────────────────────
# Constellation colour for GPS
GPS_COLOR = "#2196F3"   # GPS blue

# Figure: 2 panels sharing the time axis
fig, axes = plt.subplots(2, 1, figsize=(14, 8), sharex=True, facecolor="#0d1117")
fig.suptitle(
    f'GPS Satellite {SAT} — Auckland (AUCK00NZL), 2026-01-01',
    fontsize=14, fontweight='bold', color="#ffffff"
)

# Apply dark background to both panels
for ax in axes:
    ax.set_facecolor("#111827")
    ax.tick_params(colors="#aaaaaa")
    for spine in ax.spines.values():
        spine.set_edgecolor("#333333")
    ax.grid(True, color="#222222", linewidth=0.5)

# Panel 1 — Pseudorange

axes[0].plot(pr.index, pr.values / 1e6, color=GPS_COLOR, lw=1.8, label=f'Pseudorange ({pr_label})')
axes[0].set_ylabel('Pseudorange [Mm]', color="#aaaaaa", fontsize=11)
axes[0].set_title(
    f'Pseudorange {pr_label} — distance from receiver to satellite (in million metres)',
    fontsize=10, color="#ffffff"
)

# Annotate the closest approach (smallest pseudorange = satellite highest in sky)
idx_min = pr.idxmin()
axes[0].annotate(
    f'Closest approach\n{pr[idx_min]/1e6:.2f} Mm',
    xy=(idx_min, pr[idx_min]/1e6),
    xytext=(30, 20),
    textcoords='offset points',
    arrowprops=dict(arrowstyle='->', color="#F44336"),
    fontsize=9,
    color="#F44336"
)

axes[0].legend(fontsize=9, framealpha=0.3, facecolor="#1a1a2e", edgecolor="#444444", labelcolor="#e0e0e0")

# Panel 2 — SNR

axes[1].plot(snr.index, snr.values, color="#FFEB3B", lw=1.8, label=f'SNR ({snr_label})')

# Quality threshold lines
axes[1].axhline(40, color="#00e676", ls='--', lw=1.2, alpha=0.8, label='Excellent (40 dB-Hz)')
axes[1].axhline(35, color="#4CAF50", ls='--', lw=1.0, alpha=0.8, label='Good (35 dB-Hz)')
axes[1].axhline(25, color="#F44336", ls='--', lw=1.0, alpha=0.8, label='Poor (25 dB-Hz)')

# Shade low-SNR regions (poor quality)
axes[1].fill_between(
    snr.index, snr.values, 25,
    where=(snr.values < 25),
    color="#F44336", alpha=0.25, label='Low SNR zone'
)

axes[1].set_ylabel('SNR [dB-Hz]', color="#aaaaaa", fontsize=11)
axes[1].set_xlabel('UTC Time (HH:MM)', color="#aaaaaa", fontsize=11)
axes[1].set_title(
    'Signal-to-Noise Ratio — higher = better signal quality',
    fontsize=10, color="#ffffff"
)
axes[1].legend(
    fontsize=9, ncol=2,
    framealpha=0.3, facecolor="#1a1a2e", edgecolor="#444444", labelcolor="#e0e0e0"
)
axes[1].set_ylim(0, 60)

# Time axis formatting

axes[1].xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
axes[1].xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig('plot1_pseudorange_snr_arc.png', dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

print(f'✅ Plot saved: plot1_pseudorange_snr_arc.png')
print()
print('💡 Interpretation:')
print(f'   • The pseudorange arc shows the satellite rising, passing overhead, then setting.')
print(f'   • Minimum pseudorange ({pr.min()/1e6:.2f} Mm) = satellite was directly overhead.')
print(f'   • SNR peaks when the satellite is highest in the sky.')
print(f'   • SNR drops near the horizon (low elevation, more atmosphere to penetrate).')

# ─────────────────────────────────────────────
# Step 5 — Plot 2: SNR Heatmap (Satellite Availability)
# ─────────────────────────────────────────────
# Building SNR array
# Getting full time series including NaN (= satellite not visible)
snr_full = obs['S1C'].sel(sv=SAT).to_series()

# Replace NaN with 5 (below vmin=15) so gaps render as dark background
snr_display = np.where(np.isnan(snr_full.values), 5, snr_full.values)

# Custom GNSS colormap
gnss_cmap = LinearSegmentedColormap.from_list(
    "gnss_snr",
    [
        "#0d1117",  # background / no data
        "#1a0533",  # deep purple (very weak)
        "#2c3e8c",  # blue (low)
        "#0099cc",  # cyan (moderate)
        "#00e676",  # green (good)
        "#ffeb3b",  # yellow (strong)
        "#ff6f00",  # orange (excellent)
    ],
    N=256
)

# Figure

fig, ax = plt.subplots(figsize=(16, 3), facecolor="#0d1117")
ax.set_facecolor("#0d1117")

# ── KEY FIX: use imshow instead of pcolormesh ──────────────────────
# pcolormesh with shading='auto' silently eats the last column on a
# 1-row matrix, producing a completely blank plot.
# imshow handles 1-row data correctly via extent= for the time axis.
ax.imshow(
    snr_display.reshape(1, -1),   # shape must be (1, N)
    aspect='auto',
    cmap=gnss_cmap,
    vmin=15,
    vmax=55,
    extent=[
        mdates.date2num(snr_full.index[0]),   # x left  = first epoch
        mdates.date2num(snr_full.index[-1]),  # x right = last epoch
        -0.5,                                  # y bottom
        0.5                                    # y top
    ]
)

# Tell matplotlib the X axis contains date numbers
ax.xaxis_date()

# Colorbar
sm = plt.cm.ScalarMappable(cmap=gnss_cmap,
                            norm=plt.Normalize(vmin=15, vmax=55))
cbar = plt.colorbar(sm, ax=ax, pad=0.01)
cbar.set_label('SNR [dB-Hz]', color="#e0e0e0")
cbar.ax.yaxis.set_tick_params(color="#aaaaaa")
plt.setp(cbar.ax.get_yticklabels(), color="#aaaaaa")

# Y axis — satellite label centred in the band
ax.set_yticks([0])
ax.set_yticklabels([SAT], fontsize=11, color="#e0e0e0", fontweight='bold')
ax.set_ylim(-0.5, 0.5)

ax.set_title(
    f'SNR Heatmap — GPS {SAT} | AUCK00NZL | 2026-01-01\n'
    'Green/Yellow = strong signal  |  Blue/Purple = weak  |  Black = not visible',
    fontsize=12, fontweight='bold', color="#ffffff"
)
ax.set_xlabel('UTC Time (HH:MM)', fontsize=11, color="#e0e0e0")

ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
ax.xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")

for spine in ax.spines.values():
    spine.set_edgecolor("#333333")

plt.tight_layout()
plt.savefig('plot2_snr_heatmap.png', dpi=150, bbox_inches='tight',
            facecolor=fig.get_facecolor())
plt.show()

print('✅ Plot saved: plot2_snr_heatmap.png')
print()
print('💡 Interpretation:')
print('   • Black areas    = satellite below horizon (no tracking)')
print('   • Blue/Purple    = weak signal (low elevation or interference)')
print('   • Green          = good signal quality (> 35 dB-Hz)')
print('   • Yellow/Orange  = excellent signal (satellite directly overhead)')